{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seek.android",
    "module": "core-domain",
    "version": "0.0.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-domain-0.0.336.jar",
          "url": "core-domain-0.0.336.jar",
          "size": 21852,
          "sha512": "755fb1f2321ea1dcd14dea44ba2f01aa08007e332f94c5620bb04c679fb6e0091ef573feae7d47a712c8e129590be71ad6822bf0beb134710f166b39ccd836e1",
          "sha256": "649ce0f69f83e1ede51c3e55fe78ef4c1ca49c1c0f1d3061c1d3bd0a27d0c027",
          "sha1": "7c6cecb1cdeb00b2a4269a1ad4d4abed4e1ba9dd",
          "md5": "589209d1a70aac0ca4b8762ca2c9e6c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-domain-0.0.336.jar",
          "url": "core-domain-0.0.336.jar",
          "size": 21852,
          "sha512": "755fb1f2321ea1dcd14dea44ba2f01aa08007e332f94c5620bb04c679fb6e0091ef573feae7d47a712c8e129590be71ad6822bf0beb134710f166b39ccd836e1",
          "sha256": "649ce0f69f83e1ede51c3e55fe78ef4c1ca49c1c0f1d3061c1d3bd0a27d0c027",
          "sha1": "7c6cecb1cdeb00b2a4269a1ad4d4abed4e1ba9dd",
          "md5": "589209d1a70aac0ca4b8762ca2c9e6c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-domain-0.0.336-sources.jar",
          "url": "core-domain-0.0.336-sources.jar",
          "size": 4252,
          "sha512": "933c6f45e1417dacb71b4bfd22d709c5c5f1a44f94c839bb7ce449df96658905ce5503ad4248517dfd6602b264b6cb7c851f438710ab4b6911fd7e189a896b13",
          "sha256": "b376e6bbd94f2db628ba5ac392a28c00f442e7d27b576977aa137857ec144647",
          "sha1": "35f0db04a1d9365af2381d3acd91cc67bcaf45b2",
          "md5": "e309c6c00d3482e418b70ad8e0081fbc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-domain-0.0.336-javadoc.jar",
          "url": "core-domain-0.0.336-javadoc.jar",
          "size": 261,
          "sha512": "db96092dd14a7f0dc1d75d2ffac41a3f8c08485cdf83ea9e90d7633752d70cf3d9720d4e67eb7db684c78102cc957dee4b105bb12f7e4de04586d4cbde5015e6",
          "sha256": "b49e6f39bdb593abfa5103169a5320f99dd6dd81cc1ff96d0fee15cd0dccd56c",
          "sha1": "f4efa0a0a94a2e313aade13fc3fb5513912bfe75",
          "md5": "3485a818a4c51b91551b5173a9ac102c"
        }
      ]
    }
  ]
}
