{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seek.android",
    "module": "core-data-test",
    "version": "0.0.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-test-android",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-data",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-data-test-0.0.336-debug.aar",
          "url": "core-data-test-0.0.336-debug.aar",
          "size": 12152,
          "sha512": "4c795d2944842258ce4dd58750536f47859a85b0df8df081ed237fe6de5ee3d3f82d556512ddcf7f6b3b88d1eab6fec744313a38d9c1a3efc4dbb1ff240ce9f5",
          "sha256": "670c590a0edf6f75060482e63ad9d3623938ac7190e8b5a50641342419577db7",
          "sha1": "e8a3516096c267b313649ac035fd766da1998faf",
          "md5": "0a7b655ed988d5b671ebebf35f0fcb36"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-test-android",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-data",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-data-test-0.0.336-debug.aar",
          "url": "core-data-test-0.0.336-debug.aar",
          "size": 12152,
          "sha512": "4c795d2944842258ce4dd58750536f47859a85b0df8df081ed237fe6de5ee3d3f82d556512ddcf7f6b3b88d1eab6fec744313a38d9c1a3efc4dbb1ff240ce9f5",
          "sha256": "670c590a0edf6f75060482e63ad9d3623938ac7190e8b5a50641342419577db7",
          "sha1": "e8a3516096c267b313649ac035fd766da1998faf",
          "md5": "0a7b655ed988d5b671ebebf35f0fcb36"
        }
      ]
    },
    {
      "name": "debugVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-data-test-0.0.336-debug-javadoc.jar",
          "url": "core-data-test-0.0.336-debug-javadoc.jar",
          "size": 293875,
          "sha512": "baa573d651f8dab243ead8134139ac23736740dbefb9d013e2693748cbadbfe2ffe6ea0883f38807d3ef1ab5f9ff9468272e43185b4ad0fb4ef78bc71baed13a",
          "sha256": "5314b1ab682555b052a8915d7eebd6c5d1a8d0abc8660e7783a5344e26d35164",
          "sha1": "b1b0cd259e4bb481e663050985d66511c8047ead",
          "md5": "0fb8722cf357c74835c0431a6d6c9e21"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-test-android",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-data",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-data-test-0.0.336-release.aar",
          "url": "core-data-test-0.0.336-release.aar",
          "size": 11695,
          "sha512": "26c15b9092e312c4b82c6f6a4592a03175558c20c2e9af1da60f857b610285a2d6a8cacdc69dd2051034066c1087a049b5971180a1d895933ad4dd32718373da",
          "sha256": "56dabb21b8af9d486be35664128c4ac0ab001556a636ffa0862432b244141d09",
          "sha1": "80466ce2952e8c3fbda4928476621a8ee3ae6ba7",
          "md5": "82b11ddae56af978013e678008c090b0"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-test-android",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-data",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-data-test-0.0.336-release.aar",
          "url": "core-data-test-0.0.336-release.aar",
          "size": 11695,
          "sha512": "26c15b9092e312c4b82c6f6a4592a03175558c20c2e9af1da60f857b610285a2d6a8cacdc69dd2051034066c1087a049b5971180a1d895933ad4dd32718373da",
          "sha256": "56dabb21b8af9d486be35664128c4ac0ab001556a636ffa0862432b244141d09",
          "sha1": "80466ce2952e8c3fbda4928476621a8ee3ae6ba7",
          "md5": "82b11ddae56af978013e678008c090b0"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-data-test-0.0.336-release-javadoc.jar",
          "url": "core-data-test-0.0.336-release-javadoc.jar",
          "size": 293875,
          "sha512": "baa573d651f8dab243ead8134139ac23736740dbefb9d013e2693748cbadbfe2ffe6ea0883f38807d3ef1ab5f9ff9468272e43185b4ad0fb4ef78bc71baed13a",
          "sha256": "5314b1ab682555b052a8915d7eebd6c5d1a8d0abc8660e7783a5344e26d35164",
          "sha1": "b1b0cd259e4bb481e663050985d66511c8047ead",
          "md5": "0fb8722cf357c74835c0431a6d6c9e21"
        }
      ]
    }
  ]
}
