{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seek.android",
    "module": "core-test-android",
    "version": "0.0.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-android-0.0.336-debug.aar",
          "url": "core-test-android-0.0.336-debug.aar",
          "size": 2737,
          "sha512": "9a013084faebf74a333c6af7a3732286bf584fbb4a50485514dce7d4ff5ca72619bd5e00e65e26d477dacdcf2a41845a39d31767ee1a7f625a1162155daa8479",
          "sha256": "209ebcc4e79a1364e5bb945a78a93d925c7221a8223d9972744f74837981fe8f",
          "sha1": "2e0f6b167f1916295615132ab7e142b12f6b8f99",
          "md5": "494e8a9e767ac13f99bd21c444815c85"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "junit",
          "module": "junit"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.robolectric",
          "module": "robolectric"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-android-0.0.336-debug.aar",
          "url": "core-test-android-0.0.336-debug.aar",
          "size": 2737,
          "sha512": "9a013084faebf74a333c6af7a3732286bf584fbb4a50485514dce7d4ff5ca72619bd5e00e65e26d477dacdcf2a41845a39d31767ee1a7f625a1162155daa8479",
          "sha256": "209ebcc4e79a1364e5bb945a78a93d925c7221a8223d9972744f74837981fe8f",
          "sha1": "2e0f6b167f1916295615132ab7e142b12f6b8f99",
          "md5": "494e8a9e767ac13f99bd21c444815c85"
        }
      ]
    },
    {
      "name": "debugVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-test-android-0.0.336-debug-javadoc.jar",
          "url": "core-test-android-0.0.336-debug-javadoc.jar",
          "size": 274864,
          "sha512": "edc6b890683b552c0c464c5cdab75beb3df47575a995dff235699ceb7063eec2b26fc6f83f33a45bc0173c14614d245448544bbe85def1694ef6a0290cf2eb72",
          "sha256": "869f9bc63543070d8be0da0d9b6dcf39fa536466f562466543a44c2ffaa5ec3f",
          "sha1": "a21f0c4e395a781594e5ad5e3b35c722d6ee97ea",
          "md5": "19fff7481f1d078d2560ad5b94407eca"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-android-0.0.336-release.aar",
          "url": "core-test-android-0.0.336-release.aar",
          "size": 2635,
          "sha512": "09ed0e85c60ee818420e11bc511ab36de52a6f841cbbeda1bef3ab5fbf301825aac8e6eb4ce2a091000741c6653595f37fd0657630ea558c750831545f2b5bc3",
          "sha256": "f092ca8f573d3e06fb696eb7a717d38a4c28c68692025d7a914b50aea658f4a1",
          "sha1": "73f973bf1a5d99a9ff02a271edfdd278b9529e23",
          "md5": "89745c72a9fec371007781353b344904"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-common-test",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "junit",
          "module": "junit"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.robolectric",
          "module": "robolectric"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-android-0.0.336-release.aar",
          "url": "core-test-android-0.0.336-release.aar",
          "size": 2635,
          "sha512": "09ed0e85c60ee818420e11bc511ab36de52a6f841cbbeda1bef3ab5fbf301825aac8e6eb4ce2a091000741c6653595f37fd0657630ea558c750831545f2b5bc3",
          "sha256": "f092ca8f573d3e06fb696eb7a717d38a4c28c68692025d7a914b50aea658f4a1",
          "sha1": "73f973bf1a5d99a9ff02a271edfdd278b9529e23",
          "md5": "89745c72a9fec371007781353b344904"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-test-android-0.0.336-release-javadoc.jar",
          "url": "core-test-android-0.0.336-release-javadoc.jar",
          "size": 274864,
          "sha512": "edc6b890683b552c0c464c5cdab75beb3df47575a995dff235699ceb7063eec2b26fc6f83f33a45bc0173c14614d245448544bbe85def1694ef6a0290cf2eb72",
          "sha256": "869f9bc63543070d8be0da0d9b6dcf39fa536466f562466543a44c2ffaa5ec3f",
          "sha1": "a21f0c4e395a781594e5ad5e3b35c722d6ee97ea",
          "md5": "19fff7481f1d078d2560ad5b94407eca"
        }
      ]
    }
  ]
}
