{
  "formatVersion": "1.1",
  "component": {
    "group": "com.seek.android",
    "module": "core-presentation",
    "version": "0.0.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-domain",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-navigation",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose"
        },
        {
          "group": "seek.braid.compose",
          "module": "braid"
        },
        {
          "group": "com.google.android.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-presentation-0.0.336-debug.aar",
          "url": "core-presentation-0.0.336-debug.aar",
          "size": 267809,
          "sha512": "0a4e56aeee16790a7ae7942a518903f04008dfa67187de154051f0a965a3383f8bbb29836f7ee27104230ee42cabad4ccd1ed69c4243ccaaa333de1933c884a8",
          "sha256": "6dd68e55022d066303a5a2fd1241f299a95efb2acc67e1ff6a7d50e7217e1977",
          "sha1": "2db121107282578501e32171d6cb26b6b6f1ccbf",
          "md5": "cb9b665be27125af304a9975c829427b"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil"
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose"
        },
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-domain",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-navigation",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose"
        },
        {
          "group": "seek.braid.compose",
          "module": "braid"
        },
        {
          "group": "com.google.android.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-presentation-0.0.336-debug.aar",
          "url": "core-presentation-0.0.336-debug.aar",
          "size": 267809,
          "sha512": "0a4e56aeee16790a7ae7942a518903f04008dfa67187de154051f0a965a3383f8bbb29836f7ee27104230ee42cabad4ccd1ed69c4243ccaaa333de1933c884a8",
          "sha256": "6dd68e55022d066303a5a2fd1241f299a95efb2acc67e1ff6a7d50e7217e1977",
          "sha1": "2db121107282578501e32171d6cb26b6b6f1ccbf",
          "md5": "cb9b665be27125af304a9975c829427b"
        }
      ]
    },
    {
      "name": "debugVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-presentation-0.0.336-debug-javadoc.jar",
          "url": "core-presentation-0.0.336-debug-javadoc.jar",
          "size": 534939,
          "sha512": "ae8f7ec279c4309dbd6a9be809e7f4f334e7c21303dc2e0220048c345695d381f9242468a19c02acde69137738dac221273976a17733d9b549fccb0b3963fa55",
          "sha256": "116b0f88515f65d9ce9360c9afc2d9d555d508aa38d7ef6706157b2c2101a0df",
          "sha1": "8bfbafcac57ff8024075bed81c180bbb9ffeb7dc",
          "md5": "8676d74c2e5ba2511d0496ee7050bd68"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-domain",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-navigation",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose"
        },
        {
          "group": "seek.braid.compose",
          "module": "braid"
        },
        {
          "group": "com.google.android.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-presentation-0.0.336-release.aar",
          "url": "core-presentation-0.0.336-release.aar",
          "size": 251849,
          "sha512": "59aa5bfec78973af06add71c2afba44d06fa6d237c5b6088ee9daa3ab41634bef07747757ae3a4136a1ac793186484691d49dcfc90a3c0f8def4c2092b848c5e",
          "sha256": "5297155588782960b70db1de6df3b09efd216c6c1b68898388aaf2173fa9e9f8",
          "sha1": "98b5b6efc023866823413143c81d82c1a452fdbd",
          "md5": "c4434abb0cd5cfc9e30dcd0e833f270d"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil"
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose"
        },
        {
          "group": "com.seek.android",
          "module": "core-common",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-domain",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "com.seek.android",
          "module": "core-navigation",
          "version": {
            "requires": "0.0.336"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx"
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose"
        },
        {
          "group": "seek.braid.compose",
          "module": "braid"
        },
        {
          "group": "com.google.android.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-gradle-plugin",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-runtime",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "com.apollographql.apollo3",
          "module": "apollo-http-cache",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "seek.braid.compose",
          "module": "braid",
          "version": {
            "requires": "8.16.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-test",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "au.com.seek.hubble",
          "module": "hubble-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "au.com.seek.eventcatalogue",
          "module": "data-tracking-event-catalogue",
          "version": {
            "requires": "4.7.0-2-gaf66208"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-test",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-formatting",
          "version": {
            "requires": "1.23.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jmailen.gradle",
          "module": "kotlinter-gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.lemonappdev",
          "module": "konsist",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "1.9.22-1.0.17"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk-agent-jvm",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-multidex",
          "version": {
            "requires": "4.11.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-intents",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.espresso.idling",
          "module": "idling-concurrent",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "androidx.test.uiautomator",
          "module": "uiautomator",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "orchestrator",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "mockwebserver",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.jraska",
          "module": "falcon",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-presentation-0.0.336-release.aar",
          "url": "core-presentation-0.0.336-release.aar",
          "size": 251849,
          "sha512": "59aa5bfec78973af06add71c2afba44d06fa6d237c5b6088ee9daa3ab41634bef07747757ae3a4136a1ac793186484691d49dcfc90a3c0f8def4c2092b848c5e",
          "sha256": "5297155588782960b70db1de6df3b09efd216c6c1b68898388aaf2173fa9e9f8",
          "sha1": "98b5b6efc023866823413143c81d82c1a452fdbd",
          "md5": "c4434abb0cd5cfc9e30dcd0e833f270d"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-presentation-0.0.336-release-javadoc.jar",
          "url": "core-presentation-0.0.336-release-javadoc.jar",
          "size": 534939,
          "sha512": "ae8f7ec279c4309dbd6a9be809e7f4f334e7c21303dc2e0220048c345695d381f9242468a19c02acde69137738dac221273976a17733d9b549fccb0b3963fa55",
          "sha256": "116b0f88515f65d9ce9360c9afc2d9d555d508aa38d7ef6706157b2c2101a0df",
          "sha1": "8bfbafcac57ff8024075bed81c180bbb9ffeb7dc",
          "md5": "8676d74c2e5ba2511d0496ee7050bd68"
        }
      ]
    }
  ]
}
